# Generated by Django 5.2.17 on 2026-10-10 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='教室名稱')),
                ('capacity', models.IntegerField(verbose_name='容納人數')),
                ('equipment', models.CharField(blank=True, max_length=255, verbose_name='設備')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='借用日期')),
                ('time_slot', models.CharField(max_length=50, verbose_name='借用時段 (例: 09:00-10:00)')),
                ('status', models.CharField(default='Booked', max_length=20, verbose_name='狀態')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classrooms.classroom', verbose_name='教室')),
            ],
        ),
    ]
